# Generated by Django 5.0.1 on 2024-01-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, max_length=200, unique=True)),
                ('additional_info', models.TextField(blank=True)),
                ('ratting', models.PositiveSmallIntegerField(default=50)),
                ('book_count', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('books', models.ManyToManyField(blank=True, related_name='customers', to='books.book')),
            ],
        ),
    ]
